### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Phillbert** [ethicalhack3r/DVWA#110]
I am receiving this error when logging in for the first time on  a Windows 10 machine. 

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\DVWA-1.9\dvwa\includes\dvwaPage.inc.php:461 Stack trace: #0 C:\xampp\htdocs\DVWA-1.9\login.php(8): dvwaDatabaseConnect() #1 {main} thrown in C:\xampp\htdocs\DVWA-1.9\dvwa\includes\dvwaPage.inc.php on line 461

**Comment by XTpeeps** [comment]
+1 same question happened to me 来自360手机 On 2016-11-09 09:23 , Phillbert Wrote: I am receiving this error when logging in for the first time on a Windows 10 machine. Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\DVWA-1.9\dvwa\includes\dvwaPage.inc.php:461 Stack trace: #0 C:\xampp\htdocs\DVWA-1.9\login.php(8): dvwaDatabaseConnect() #1 {main} thrown in C:\xampp\htdocs\DVWA-1.9\dvwa\includes\dvwaPage.inc.php on line 461 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mike-bailey** [comment]
All mysql_connect references have been removed over time since this issue. Feel free to reopen issues if you have any other issues with this project or this issue isn't resolved.
