### ISSUE TITLE
DVWA on PHP version: 7.0.9-2 cannot solve default installation errors

### ISSUE THREAD

**Issue by betty5588** [ethicalhack3r/DVWA#134]
I was trying the fix the errors for (1)Allow_url_include (2) PHP module gd missing (3) reCaptcha key missing 

Operating system: *nix
Backend database: MySQL
PHP version: 7.0.9-2
PHP function display_errors: Disabled
PHP function safe_mode: Disabled
**PHP function **allow_url_include: Disabled****
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
**PHP module gd: Missing**
PHP module mysql: Installed
PHP module pdo_mysql: Installed
**reCAPTCHA key: Missing**

(1)Cannot find "Allow_url_include" in this ini file
root@KaliLinux:/etc/php/7.0/apache2# nano php.ini 

(2)Cannot locate and install "PHP module gd"
root@KaliLinux:/var/www/html/DVWA/external/phpids/0.6/lib/IDS# apt search php7-gd
Sorting... Done
Full Text Search... Done
root@KaliLinux:/var/www/html/DVWA/external/phpids/0.6/lib/IDS# apt-get install php7-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7-gd

(3)How to resolve missing reCaptcha key?

Thank you

**Comment by betty5588** [comment]
System 	Linux KaliLinux 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64
Server API 	Apache 2.0 Handler
Virtual Directory Support 	disabled
Configuration File (php.ini) Path 	/etc/php/7.0/apache2
Loaded Configuration File 	/etc/php/7.0/apache2/php.ini
Scan this dir for additional .ini files 	/etc/php/7.0/apache2/conf.d

**Comment by tastypastryyum** [comment]
I have this same issue, trying to resolve but I haven't had any luck yet. Was hoping when I saw this thread there would be an answer in it. 
I found this page
https://secure.php.net/manual/en/filesystem.configuration.php#ini.allow-url-include
Essentially you have to turn the allow_url_include file to "on", I haven;t figured out how to do this yet but hope it helps you and if ya do figure it out lemme know!

**Comment by tastypastryyum** [comment]
I just spent the last 20 minutes searching for the damn allow_url_include with no luck, it's gotta be in there somewhere. I think I might have been looking in the wrong place, cant tell just yet

**Comment by digininja** [comment]
I'll let you know where it is this evening when I've got my laptop out

**Comment by tastypastryyum** [comment]
Hey no rush.

If this helps you decipher the problem. 

So I was in /etc/php/7.0/apache2, I was doing some other research online and found this relatively helpful link..
https://my.bluehost.com/cgi/help/377
After reading I realized I wasn't supposed to be searching for `allow_url_include` necessarily but that I needed to added that into the php.ini script. I did however, find where `allow_url_include` is located in the php.ini file, if you put set numbers (if you use vim) on and go to line 828 (at least for me) you'll find it there as well as allow_url_fopen.
So before I edited anything the allow_url_include was off so I turned it on and then added `allow_url_include = 1`to a new line..not sure if I needed to do both, turing off, to on, and adding `allow_url_include = 1` or not but I did and I still have the "PHP function allow_url_include: Disabled" option showing up. Maybe I need to restart mysql? Idk how to do that but I'll figure it out after this message. So that's all I've tried so far, no rush in a response I just really appreciate the fact that you even read the message! Any help would be greatly appreciated, thank you !

**Comment by tastypastryyum** [comment]
WOOOH!

So I know I've kinda been spamming this thread but I got it to work !
I think the trick was restarting mysql and restarting apache2 because now i have 

PHP function allow_url_include: Enabled

In the php.ini file I edited it and have it as...

allow_url_fopen = On
allow_url_fopen = 1

allow_url_open = On
allow_url_open = 1 

Once I did that I also copied the edited php.ini file into /var/www/html/dvwa/config so the new php.ini file was in the dvwa/confg directory.

**Comment by tastypastryyum** [comment]
I still have a few other issues unfortunately;

PHP module gd: Missing
reCAPTCHA key: Missing
[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: No
[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: No

Will do my best to figure out on my own but any advice would be awesome,

**Comment by digininja** [comment]
the php.ini in the config directory won't do anything, you can get rid of
that. You don't need to restart mysql, that is the database, the setting is
for php. You should be able to drop the duplication and have either On or 1.

The writable directory/file is easy, The standard answer is to give them
777 and 666 permissions in turn. The correct way is to leave them at 755
and 644 and set the ownership .

recaptcha key, go to google and get a recaptcha key then add it to the
config file. Not sure if this has been updated since google updated the
captcha to the latest version.

gd, install the php gd module.

After installing modules or setting flags, make sure you restart apache.

**Comment by tastypastryyum** [comment]
Awesome thanks so much.

For the writable folder do I simply need to `chmod 755 /var/www/html/dvwa/hackable/uploads/` 
and for writable folder `chmod644 /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt` ?? 
I assume thats the path but not sure if that is specifically what I need to change permissions on or if I need to change permissions via a different path or a different file type

**Comment by digininja** [comment]
Folder then file, if those are the directories it is asking you to set the
permissions on then they are the ones. You can install to anywhere so can't
tell you your definite location without access to your machine or more info

**Comment by tastypastryyum** [comment]
Alright, thank you. 
It now reads yes for folder but not getting the file rewritten correctly. The first attempt to rewrite permission for the file I gave the wrong path, the path then disapeared on the dvwa setup page, that doesnt seems good, anyway to reset that via dvwa or CLI?

**Comment by digininja** [comment]
chmod 666 <the file> will fix the file write problem. Check for errors when
running the command

**Comment by tastypastryyum** [comment]
So I keep getting no as a response from dvwa no matter how many times rewrite it

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: Yes
[User: root] Writable file : No

You can see now that the path isn't even showing up. 
I did what you said, `chmod 666 /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt`..weird thing is that I dont get any errors back when I put this in, the system accepts it but nothing changes on dvwa. I even restarted everything and tried changing the permission to 755 for the file but it still says no, really stumped, I obviously effed something up. Anything I can do to give you a better idea of what I did wrong?

**Comment by tastypastryyum** [comment]
Here's a list of a few commands I just ran. tried to chmod again, I cat the path, ls it

root@kalikali:~# chmod 666 /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt

root@kalikali:~# cat /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt
"local/unknown",2010-03-15T23:07:01+00:00,72,"xss csrf id rfe lfi sqli","REQUEST.test=%22%3E%3Cscript%3Eeval%28window.name%29%3C%2Fscript%3E GET.test=%22%3E%3Cscript%3Eeval%28window.name%29%3C%2Fscript%3E","%2Fdvwa%2Fsecurity.php%3Ftest%3D%2522%253E%253Cscript%253Eeval%28window.name%29%253C%2Fscript%253E","127.0.0.1"

root@kalikali:~# ls /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt
/var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt

root@kalikali:~# ls -l /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt
-rw-rw-rw- 1 root root 319 May 12 10:43 /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt

**Comment by tastypastryyum** [comment]
So I definitely fucked something up, figures. I rm dvwa and reinstalled then did all the steps over again and paid attention to what I was typing and got the writable folder/file to read yes.

Can't get the PHP gd module to work thou, everytime I try to `apt-get install php5-gd` I get back..

apt-get install php5-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php5-gd

Am I trying to download the incorrect version ? I'm not entirely sure I know which version I have..obviously an issue. Any ideas ?

**Comment by digininja** [comment]
Didn't you say you were using php 7? That is the php 5 library.

Use apt-cache search to find and install the php7 equivalent.

**Comment by tastypastryyum** [comment]
When I go to localhost/dvwa/ and click "create/reset database"

I get back "Could not connect to the MySQL service. Please check the config file."

Here is the output from the dvwa server setup page

Operating system: *nix

Backend database: MySQL

PHP version: 7.0.16-3

Web Server SERVER_NAME: localhost

PHP function display_errors: Disabled

PHP function safe_mode: Disabled

PHP function allow_url_include: Enabled

PHP function allow_url_fopen: Enabled

PHP function magic_quotes_gpc: Disabled

PHP module gd: Missing

PHP module mysql: Installed

PHP module pdo_mysql: Installed

MySQL username: root

MySQL password: **********

MySQL database: dvwa

MySQL host: 127.0.0.1

reCAPTCHA key: "I have this correct but wont post the key"

[User: root] Writable folder /var/www/html/dvwa/hackable/uploads/: Yes

[User: root] Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

It seems like the issue might be that I dont have the PHP module installed but whenever I try and "apt-get install php 7.0" or anything I keep getting an error saying .... E: Couldn't find any package by glob '7.0.-gd' E: Couldn't find any package by regex '7.0.-gd' I tried to do the PHP version listed at the top "php7.0.16-3" and I still get the same error. Do I have the syntax wrong ? I'm really stumped here. Maybe I messed something else up which is why it's saying "could not connect to mysql server" When I run service mysql start and even when I do a status check for mysql everything is good to go though...obviously I've made sure that I am running mysql before I go to localhost/dvwa/ and apache2 so I'm not sure whats wrong here﻿..

**Comment by digininja** [comment]
Could not connect to MySQL means it can't connect to the database. Make
sure it is running and that you can connect using the credentials you
provide in the config file.

**Comment by tastypastryyum** [comment]
Alright so I thought I was having issues with not having the correct credentials so I went and changed the password. Weird thing is that after doing so when I `mysql -u root -p` and enter any random combination it goes right into, 


`root@kali:~#` mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 33
Server version: 10.1.22-MariaDB- Debian 9.0

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> `

This makes me believe I messed something up along the way while reseting the password but I didn't get any errors while doing so. 

To ensure that mysql is running are there any other commands I can do aside from `service mysql status` ? When I enter that command I get a positive status of 
`root@kali:~# service mysql status
● mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql; generated; vendor preset: disabled)
   Active: active (running) since Mon 2017-05-15 17:36:20 EDT; 3min 49s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11337 ExecStop=/etc/init.d/mysql stop (code=exited, status=0/SUCCESS)
  Process: 11370 ExecStart=/etc/init.d/mysql start (code=exited, status=0/SUCCESS)
    Tasks: 29 (limit: 19660)
   CGroup: /system.slice/mysql.service
           ├─11399 /bin/bash /usr/bin/mysqld_safe
           ├─11543 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/x86_64-linux-gnu/mariadb18/plugin --user=mysql
           └─11544 logger -t mysqld -p daemon error

May 15 17:36:19 kali mysqld[11544]: 2017-05-15 17:36:19 139989085090368 [Note] Plugin 'FEEDBACK' is disabled.
May 15 17:36:19 kali mysqld[11544]: 2017-05-15 17:36:19 139988486293248 [Note] InnoDB: Dumping buffer pool(s) not yet started
May 15 17:36:20 kali mysqld[11544]: 2017-05-15 17:36:20 139989085090368 [Note] Server socket created on IP: '127.0.0.1'.
May 15 17:36:20 kali mysqld[11544]: 2017-05-15 17:36:20 139989085090368 [Note] /usr/sbin/mysqld: ready for connections.
`
When I changed the password I made sure to go back into the config file and update the password so they match but I'm still getting the error of cannot connect to database

Think I should delete the Kali VM and start over?

**Comment by digininja** [comment]
"Think I should delete the Kali VM and start over?"

Depends if you fancy a challenge or not. I'd take this as a learning
opportunity and debug it out till it works. Things I'd try:

You can pass the password on the command line with -p<password> no space
after the -p. Try that and see what happens.

Try changing the config file to try localhost, 127.0.0.1 and to the IP.

Connect on the command line and run some SQL.

Write your own little php app using snippets from php.net to see if it can
connect. Watch the apache error log while doing it to spot issues

**Comment by tastypastryyum** [comment]
I've been looking at the status output for mysql and this seems to stand out, 

`  Loaded: loaded (/etc/init.d/mysql; generated; vendor preset: disabled)`
I saw some syntax on youtube of other people running a status check for mysql and they didn't have that in theirs so that definitely cant be good 
I used `update-rc.d mysql enable` thinking maybe that would enable what was disabled but even after i restarted mysql I still see the disabled notice there

**Comment by digininja** [comment]
If you can connect to it from the command line then it is running, that
line doesn't look like anything I'd be worried about.

**Comment by tastypastryyum** [comment]
Hey not sure if this question is relevant to the this thread but I wanted to ask anyway.

When I Downloaded DVWA off the site I've noticed that it says 

root@kali:~/Downloads# ls
DVWA-master  DVWA-master.zip

I've watched almost every video on youtube, and blog after blog on stackoverflow and everywhere else on DVWA installation and none of them have their dvwa as `DVWA-master.zip` or, once they unzip it like I have, `DVWA-master`

Is it supposed to be like this ? What I mean in particular is I find it odd that I Dont have a "version" of DVWA like the videos and blogs I've seen.

I see a lot of `dvwa-1.0.8` or `dvwa1-0.9` etc, nowhere have I Found what I have..

Is there a command I can use to check the version of dvwa I have ? 

I tried 

`DVWA-master -v` with no luck

**Comment by tastypastryyum** [comment]
I think my issue is that I don't have a mysql database created. In my terminal I can start mysql and run a status check which returns an active and running message to my screen. I Dont think this necessarily means that I have mysql setup to communicate with dvwa if that makes sense. 

I was never prompted in my Kali Linux install to create a mysql username and password, or anything like that. I was, however, prompted to create a domain name and HTTP proxy server, is mysql one of those two ? If so what should I do when prompted with that in the install ? If neither the Domain name or HTTP proxy server are how I create a mysql account then how do I do that? 

I've read that Kali comes installed with mysql but when I run..

`root@kali:/var/www/html/dvwa/config# mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 47
Server version: 10.1.22-MariaDB- Debian 9.0

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> ` 

I am sent into a mariadb..which I dont know much about but isnt the same as mysql...

I was reading another article here which you commented on, https://github.com/ethicalhack3r/DVWA/issues/114 in which you state that if we are running mariadb then we should have that in the config.inc.php file in the part where it asks for what server we are running.

If I understand you correctly what you are saying is that in the config.inc.php where I have

`$_DVWA[ 'db_database' ] = 'dvwa'`

it instead, should be

$_DVWA[' db_database' ] = 'mariadb'

correct? 

  It seems to me that although I can run mysql and even prove its running and active that it's not communicating with dvwa like I said which leads me to believe that I need to do something to get it communicating with dvwa...is there a file I need to configure other than config.inc.php?  Because when I run... 

`root@kali:/var/www/html/dvwa/config# apt-cache show mysql 
N: Unable to locate package mysql 
E: No packages found 
root@kali:/var/www/html/dvwa/config# apt-cache show mysql-server
N: Can't select versions from package 'mysql-server' as it is purely virtual 
N: No packages found`

 But when I run that same command for apache2 I get this... 

`root@kali:/var/www/html/dvwa/config# apt-cache show apache2 
Package: apache2 
Version: 2.4.25-3 `

And a while bunch more info as well
Even though I'm in the config directory under dvwa it does the same thing when I am root, trust me I went back to my root directory and tried
I'm going to do some research via goole and stackoverflow but your help would be greatly appreciated.

**Comment by digininja** [comment]
These are the packages on my box that works fine

```
$ php -v
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies

$ dpkg --get-selections |grep php
libapache2-mod-php7.0                           install
php-common                                      install
php-mongodb                                     deinstall
php-pear                                        install
php-xml                                         install
php7.0                                          install
php7.0-cli                                      install
php7.0-common                                   install
php7.0-curl                                     install
php7.0-fpm                                      install
php7.0-gd                                       install
php7.0-json                                     install
php7.0-mysql                                    install
php7.0-opcache                                  install
php7.0-readline                                 install
php7.0-xml                                      install
```
Try this script, see if it connects or gives you a failure message:

```
<pre>
<?php

require ("config/config.inc.php");

var_dump ($_DVWA[ 'db_server' ] );
var_dump ($_DVWA[ 'db_database' ]);
var_dump ($_DVWA[ 'db_user' ]  );
var_dump ($_DVWA[ 'db_password' ]);

$link = mysqli_connect($_DVWA[ 'db_server' ], $_DVWA[ 'db_user' ] , $_DVWA[ 'db_password'], $_DVWA[ 'db_database' ]);

if (!$link) {
    echo "Error: Unable to connect to MySQL." . PHP_EOL;
    echo "Debugging errno: " . mysqli_connect_errno() . PHP_EOL;
    echo "Debugging error: " . mysqli_connect_error() . PHP_EOL;
    exit;
}

echo "Success: A proper connection to MySQL was made! The " . $_DVWA[ 'db_database' ] . " database is great." . PHP_EOL;
echo "Host information: " . mysqli_get_host_info($link) . PHP_EOL;

mysqli_close($link);
?>
```

To test your database connection you can do this

```
 mysql -u dvwa -pxxx -D dvwa -e "select * from users"
```

replace the xxx with your password, no space after the -p. Make sure you copy and paste the creds from config/config.inc.php, don't retype them as you might miss a typo.

**Comment by tastypastryyum** [comment]
I know this is a stupid question but when you ask me to try the script above where exactly should I enter it ? I know I know I just dont want to muck anything up more than I already have. 

You might find this interesting, I had uninstalled php7.0 prior to reading your article about the fact that dvwa will work with php7.0. So I reinstalled it, and that that command you have. 

`root@kali:~# dpkg --get-selections |grep php
libapache2-mod-php7.0				install
php-common					install
php7.0						install
php7.0-cli					install
php7.0-common					install
php7.0-json					install
php7.0-opcache					install
php7.0-readline					install`

That's everything...and I uh..dont see php7.0-mysql or php7.0-gd in there!! 

That cant be good !

Do I not have it installed ? I dont think that the case because I can start mysql and do a status check which gives an active and running message...

**Comment by digininja** [comment]
The missing library is how php talks to MySQL, without it you won't have
any database access.

You put the file in the root of the site, call it anything you want, then
browse to it.

**Comment by tastypastryyum** [comment]
I know this makes me look like a complete idiot but by root of the site do you mean put the script in the dvwa directory under /var/www/html/dvwa? Name it anything like you said then open the file then edit as needed?

**Comment by digininja** [comment]
The document root is wherever Apache looks for files so that is probably
right.

Call it testmysql.php and put those contents in somehow. I'd use vim but
use gedit or nano or wherever you are used to.

**Comment by tastypastryyum** [comment]
So on the dvwa setup page everything is green minus the reCAPTCHA key.

`root@kali:~# mysql -u dvwa -pmynewpassword -D dvwa -e "select * from users"`
`ERROR 1698 (28000): Access denied for user 'dvwa'@'localhost'`
`root@kali:~# mysql -u dvwa -p -D dvwa -e "select * from users"`
`Enter password: `
`ERROR 1698 (28000): Access denied for user 'dvwa'@'localhost'`
`root@kali:~# mysql -u dvwa -p -D dvwa -e "select * from users"`
`Enter password: `
`ERROR 1698 (28000): Access denied for user 'dvwa'@'localhost'`
`root@kali:~#` 

I watched a video on how to reset your mysql password and reset it to "mynewpassword" but something isn't right, I checked and double checked.

I have the correct php-gd module now, is that what you meant by "The missing library is how php talks to MySQL, without it you won't have any database access."?

I also copy and pasted that script into my `/var/www/html/dvwa` directory but nothings changed on the dvwa page when I click create database. Then I moved `testmysql.php` into my config directory alongside `config.inc.php` and `config.inc.php.dist` files 

I thought I should have put in the same information that I have in my `config.inc.php` file into the new script `testmysql.php` like the server, database, user, and password but it doesnt seem like that belongs in the script.

**Comment by digininja** [comment]
First mynewpassword is not the password for the dvwa MySQL account, did you
see the "Access denied" messages?. Have you added a dvwa database user?
There isn't one by default, the only account there is root. You have to get
that working and not showing an error before DVWA will work. My guess is
that you have been trying to use the dvwa username in the config file but
then connecting on the command line with root.

The gd library is for graphics, nothing to do with MySQL, just ignore that
for now. Also ignore the captcha, you only need that for one vulnerability.

The fact everything else is green means you've got all the other libraries
installed, thats good.

The file I gave you, put it in the dvwa directory, don't add anything to
it, just browse to it. It pulls the credentials from the DVWA config file
and tests them. If it gives errors then DVWA won't work, if it is
successful then it there is a good chance that DVWA will work. It won't
affect DVWA, nothing will change.

**Comment by mike-bailey** [comment]
19 days w/o response, and this isn't an issue with the codebase. Closing. @tastypastryyum feel free to open another issue if you have any issues with DVWA.

**Comment by Beeq1** [comment]
it says my PHP module gd: Missing can someone how me the how to get  PHP module gd iv been tring for day please help

**Comment by mike-bailey** [comment]
@Beeq1 This is your last warning. **STOP USING OTHER PEOPLE'S ISSUES FOR YOUR OWN.** You also haven't responded to the last one.

>it says my PHP module gd: Missing can someone how me the how to get PHP module gd iv been tring for day please help

You just said 30 minutes ago you couldn't get it running? How have you been seeing this for a day?

Either open a new issue or use your existing open one. Don't use other people's issues.
