### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by digininja** [ethicalhack3r/DVWA#156]
Just looking through some of the vulns and noticed that all the ones I'm working on are hard coded for MySQL, there is no PostgreSQL mentioned anywhere. Should we keep the PostgreSQL support or drop it? Would be nice to keep it but it will need some work to get it actually working.

**Comment by ethicalhack3r** [comment]
It was an old idea of mine that I never managed to fully implement. The idea was for DVWA to support multiple DBMSs so that students could use different DBMSs in the SQLi challenges and note the differences in exploitation between them.

IMO even if it was to be developed now, it would probably be best to remove all the old PostgreSQL code and start a fresh.

**Comment by digininja** [comment]
Agreed.

I've only ever worked with PostgreSQL along with Metasploit and never liked
it. It would be good to find someone who is good with it to do a proper
job. Know anyone?

**Comment by digininja** [comment]
don't think this is going to be taken up so closing.
