### ISSUE TITLE
Possible issue with banning implementation 

### ISSUE THREAD

**Issue by CryptSkitty** [ethicalhack3r/DVWA#228]
So I was doing a VERY basic brute-force with burp suite and managed to crack all of the difficulty levels.
Literally no stealth was used:
http://www.hackingarticles.in/brute-force-website-login-page-using-burpsuite-beginner-guide/

This should not be. I assume that this might stem from the fact that I am hosting DVWA on my attacking machine, 127.0.0.1. I'm installing it on another box to confirm later tomorrow. Didn't know if I should post here or not.  Will likely remove by tomorrow.

**Comment by digininja** [comment]
There is nothing wrong with publishing your solution, there are plenty out
there.

The defences built in are from guessing by hand on the site rather than
using tools as they are based on sleeping before returning the site. The
impossible level shouldn't be able to be hit in this way as it has an
account lockout for 15 minutes after 3 failed attempts so unless the right
password is in the top 3 then it should fail.

**Comment by mike-bailey** [comment]
I recommend trying to hit it manually and seeing if it locks you so you know the cookies are set properly.

**Comment by CryptSkitty** [comment]
False alarm. I encountered the same behavior on the virtualized machine, so it wasn't that. I did as Mike suggested and the lockout worked. So after that I looked at my burp intruder setting and realized that I had not re-targeted the portal after changing the secure setting.

Sorry to waste your time.

p.s. If I re-write the target to be GET, and remove the cookie, the brute force still works on impossible. Is this a feature, or am I just cheating? :^)

**Comment by digininja** [comment]
If you remove both cookies then your security level defaults to whatever
you have it set to in the config file. The impossible lockout is handled in
the database so once you are locked out the account is locked out and it
shouldn't matter what you do with the session cookie.

Unless you mean that you can log into DVWA after a lock out, in which case,
yes, the main login doesn't check the lock out.

And changing to GET rather than POST on impossible won't help you get in as
the username and password are both pulled from POST variables so the login
will fail. You might get errors displayed when you try to login as the page
doesn't check that the password and username elements are set in the POST
array, I've just submitted a PR to fix that.

**Comment by CryptSkitty** [comment]
Just to confirm, I am bruteforcing the module, not the initial login page. 

I think it was a case of me using the old cookie. Cleared the old cookies from the browser, but used it in the target(included in screencap). After locking myself out, I attempted the bruteforce again using the target from security=low, and it still worked. I'm lost at this point so I'll leave it to you to close the thread. Sorry if I'm being incoherent, just really new to the webapp game.
![screenshot from 2018-03-29 09-58-26](https://user-images.githubusercontent.com/37889906/38093167-27f00dda-3338-11e8-8b78-713b78ba8052.png)

**Comment by digininja** [comment]
The lockout is only checked at the impossible level so dropping back down
to low will allow you to brute force again.

Feel free to ask questions like you are doing, it is better than the
regular posts of "something is red, it doesn't work" that we usually have
to deal with. Wish everyone put this much effort in.

**Comment by CryptSkitty** [comment]
Okay, just reattempted this using NEW phpsessionid and got an error from burp:
(The basic request does not contain a blank line, so is not valid, etc.)

I ignored it and burpsuite silently failed, then crashed. I assume this is business as usual for DVWA, so I'm just gonna mark this as closed. Thanks for walking me through this guys.
Also @digininja , my OSCP course starts saturday, so you better believe I'll be here showing DVWA some weird love. I'll keep an eye out for any potentially weird behavior.

**Comment by digininja** [comment]
Feel free to raise tickets on bugs but pull requests are even better.

I don't know how much OSCP focuses on web apps, I thought most of it was
infrastructure.

**Comment by CryptSkitty** [comment]
It is, but they don't turn up their nose at web-app sec. Kind of a "any port in a storm" mentality. At least, that's what I gather from err..leaked material I may have found. 
My php skills are college grade, which is to say god-awful, but as I feel more confident in my ability to securely code php, I'd love to help contribute going forward.

Cheers
