### ISSUE TITLE
CSRF Token issue

### ISSUE THREAD

**Issue by F1Racer68** [ethicalhack3r/DVWA#292]
I have an installation question/issue....

I am installing DVWA on 2 separate web servers behind a Load Balancer/WAF. Connecting to the individual servers physical IP address works fine, but when I try to connect to the virtual IP address supplied by the load balancer, I am unable to log in to DVWA, constantly getting a CSRF Token issue.

I am assuming that the issue has to do with the SQL database/IP Address, but am at a loss as to how to resolve it. Any info on how I should be installing for this scenario?

Thanks.

**Comment by digininja** [comment]
The problem is probably because one of the sites will be issuing the csrf
token then the submission goes to the other site which doesn't recognise it
and so rejects the request.

Nothing to do with the database, all to do with PHP session management.

You might be able to fix it by having the session files written to a shared
drive but you might then get locking or overwritting problems.

Why are you doing the setup like this? What do you want to achieve?

**Comment by F1Racer68** [comment]
It's for demonstration/training purposes.

I am building a training lab environment for a WAF product. THis has worked for us in the past with older versions of DVWA and an older Bitnami Wordpress stack, but with the current updated Linux/Wordpress stack and latest DVWA release I am now getting this issue.

I'm just trying to figure out what has changed, and how I can fix it.

**Comment by digininja** [comment]
It might be the the last load balancer you used guaranteed to keep requests
from each client tied to a specific destination.

Without keeping the requests going to the right server, the sessions won't
match up and things won't work

**Comment by F1Racer68** [comment]
Is there any way to stop DVWA from using the CSRF tokens?

**Comment by digininja** [comment]
You could but it still wouldn't work as you need the session to be right to
keep track of you being logged in.

**Comment by mike-bailey** [comment]
Usually this is shared by synchronizing a session state across multiple servers on the load balancer. In any event, while a valid filing IMO, not a DVWA issue so not saying open.
