### ISSUE TITLE
(127.0.0.1/) localhost/dvwa/login.php BLANK

### ISSUE THREAD

**Issue by omgoma** [ethicalhack3r/DVWA#71]
To all who can help.  

I've seen this issue has been posted before however, there has not been any resolution.  I installed DVWA on XAMPP but, when I try to go to localhost/dvwa in the browser it sends me to the localhost/dvwa/login.php web page which is blank.  I've manually typed localhost/dvwa/setup.php in the browser and that page comes up fine.  So does, instructions.php and about.php.  Can anybody help me with this issue.

More info:

Setup Check is showing the following information.  Should some of the processes that are coming up as disabled be enabled.  If so, how can I resolve this issue?  

Operating system: Windows 
Backend database: MySQL
PHP version: 5.6.19

Web Server Server_Name: localhost

PHP function display_error: Enabled (Easy Mode!)
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Instaled

reCAPTCHA key: Missing

Writable folder C:\xampp\htdocs\dvwa/hackable/uploads/: Yes)
Writable file C:\xampp\htdocs\dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

DVWA was installed on a system running Windows 8

**Comment by Unskilled** [comment]
Since you have display_error enabled, check the log file for problems:
$APACHE_LOG_DIR/error<#>.log

In my case, I noticed that PHP was complaining about not being able to access multiple PHP files with the "Permission denied" error. I changed the owner of the _dvwa_ folder to the user with the appropriate permissions for these files and it started working well. I hope this works for you!

**Comment by ivipuls** [comment]
Are you using php v7.0? 
Read http://localhost/dvwa/instructions.php
"_Note, You are unable to use PHP v7.0 or later with DVWA._"

**Comment by jitsoftdeveloper** [comment]
@ivipuls i am having the same issue but i have setup everything correct. Here see my setup check shows everything is green but login page is blank and yes i installed php v7.0 because php and php5 didn't worked for me.
So is there any way to run dvwa on php v7.0 ?

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.10-1

Web Server SERVER_NAME: localhost

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Installed

reCAPTCHA key: 6LfIKwcUAAAAAN2y3n8vXUURhPIOe7QjRGOL7_fZ

Writable folder /var/www/html/dvwa/hackable/uploads/: Yes)
Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

**Comment by syllas1** [comment]
same problem here... blank page...

**Comment by uhlyarikp** [comment]
I had same problem.
Solution: enable pdo driver in php.ini

**Comment by syllas1** [comment]
Already did that mate but still blank page. After that I did restart mysq and apache2 and nothing. If i enter in localhost/DVWA-1.9/php.setup... shows:

Setup Check

Operating system: *nix
Backend database: MySQL
PHP version: 7.0.12-1

Web Server SERVER_NAME: 192.168.1.66

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Disabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Installed

reCAPTCHA key: Missing

Writable folder /var/www/html/DVWA-1.9/hackable/uploads/: No
Writable file /var/www/html/DVWA-1.9/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: No

Status in red, indicate there will be an issue when trying to complete some modules.

**Comment by uhlyarikp** [comment]
I found it in readme: "Note, You are unable to use PHP v7.0 or later with DVWA."

**Comment by digininja** [comment]
I'm using it with php 7 without any problems.

**Comment by digininja** [comment]
I've got the latest git version running find in php7 so it shouldn't be
that. Can you check your error log?

**Comment by ethicalhack3r** [comment]
Closing
